#!/usr/bin/env python3
"""Serve a directory over HTTP as application/octet-stream, like GitHub release
assets, so CI can pipe the installers the way users do. Usage: serve DIR PORT"""
import http.server
import os
import sys


class Handler(http.server.SimpleHTTPRequestHandler):
    def guess_type(self, path):
        return "application/octet-stream"

    def log_message(self, *args):
        pass


os.chdir(sys.argv[1])
http.server.ThreadingHTTPServer(("127.0.0.1", int(sys.argv[2])), Handler).serve_forever()
